GET http://localhost:3000/halls
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDUyNTllNzM2MzlkMzdmYjg2N2NjZDEiLCJpYXQiOjE2ODMxMjQzMjN9.CSRxlEDMwsz-t2p5Yy0HbrtzWL19uNH7GUMusnn8Gbw
###

POST http://localhost:3000/halls
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDUyNTllNzM2MzlkMzdmYjg2N2NjZDEiLCJpYXQiOjE2ODMxMjQzMjN9.CSRxlEDMwsz-t2p5Yy0HbrtzWL19uNH7GUMusnn8Gbw


{
    "name": "first hall" , 
    "building": "first building" , 
    "absorptiveCapacity": 50
}
###

PATCH http://localhost:3000/halls/64527e24b42e34f397c20bb0
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDUyNTllNzM2MzlkMzdmYjg2N2NjZDEiLCJpYXQiOjE2ODMxMjQzMjN9.CSRxlEDMwsz-t2p5Yy0HbrtzWL19uNH7GUMusnn8Gbw


{
    "name": "bbbb Hall"
}
### 

DELETE http://localhost:3000/halls/64527e24b42e34f397c20bb0
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDUyNTllNzM2MzlkMzdmYjg2N2NjZDEiLCJpYXQiOjE2ODMxMjQzMjN9.CSRxlEDMwsz-t2p5Yy0HbrtzWL19uNH7GUMusnn8Gbw

###




// the events request


GET http://localhost:3000/events
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDUyNTllNzM2MzlkMzdmYjg2N2NjZDEiLCJpYXQiOjE2ODMxMjQzMjN9.CSRxlEDMwsz-t2p5Yy0HbrtzWL19uNH7GUMusnn8Gbw
###

POST http://localhost:3000/events
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDUyNTllNzM2MzlkMzdmYjg2N2NjZDEiLCJpYXQiOjE2ODMxMjQzMjN9.CSRxlEDMwsz-t2p5Yy0HbrtzWL19uNH7GUMusnn8Gbw

{
    "name": "thired event" , 
    "attendeesNumber": 20 , 
    "hallId": "644d6233cf794a2f05cbf006" , 
    "description": "osid osid osid" , 
    "Date": "5/1/2023" , 
    "startTime": 1 , 
    "endTime": 2
}
###

DELETE http://localhost:3000/events/645280220373fb54f781226e
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDUyNTllNzM2MzlkMzdmYjg2N2NjZDEiLCJpYXQiOjE2ODMxMjQzMjN9.CSRxlEDMwsz-t2p5Yy0HbrtzWL19uNH7GUMusnn8Gbw
###

PUT  http://localhost:3000/events/64502cc47f40343c42611f7a
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDUyNTllNzM2MzlkMzdmYjg2N2NjZDEiLCJpYXQiOjE2ODMxMjQzMjN9.CSRxlEDMwsz-t2p5Yy0HbrtzWL19uNH7GUMusnn8Gbw

{
    "name": "bvc Event",
    "Date": "5/1/2023",
    "hallId": "644d6233cf794a2f05cbf006",
    "description": "mohab osid osid",
    "attendeesNumber": 20 
}
###



// the authentication

GET http://localhost:3000/users
###

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "first event" , 
    "email": "mhab@gmail.com",
    "password": "123454234"
}
###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "mohab@gmail.com",
    "password": "123454234"
}
###



DELETE http://localhost:3000/users/delete/64525770cf452da673289293
###

